### ISSUE TITLE
[Anon] Bug report: HoRKT-Tau.catz - Points incorrect for Tau Crisis Shas'vre upgrades

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-heralds-of-ruin-killteam#45]
**File:** HoRKT-Tau.catz

**BattleScribe version:** 1.15.09

**Platform:** Windows

**Dropbox:** No

**Description:** Team leaders: Tau Crisis Shas'vre is currently listed as 42 points, with 7th edition it should be 32 points. 
Special: Tau Crisis Shas'ui is currently listed as 32 points, with 7th edition it should be 22 points.

**Comment by Jery77** [comment]
They both have 2 flamers,  5*2 points.
Everything is ok

**Comment by Vrahn** [comment]
This is still incorrect, the issue comes when you select secondary weapons, for example:

The Shas'vre comes with 2 flamers (Base 32 + 5 + 5 = 42)

However the listed cost for a Plasma Rifle is 15 points when it should be 10 as represented in the actual rules. So if you switch out your flamer for a plasma rifle for example you're actually ending up paying: 42 + 15 when in reality it should be 42 + 10 to account for that extra cost, and that is what is actually listed.

**Comment by Vrahn** [comment]
Also, Sniper Drones from the Sniper Drone Team should cost 15 points but currently cost 0 points.

**Comment by OftKilted** [comment]
The base cost for the Tau Crisis Shas'vre is 42.
The 'Flamers' are a 0 cost option (they're included), but aren't done as a 'default selection' in the catalog. (They aren't a 5 point option.)
The points costs for the Plasma Rifle is incorrect at 15, and should be 10.
This is the same for the Missile Pod and Fusion Blaster (they both register at 5 points higher than they should be).
https://www.dropbox.com/s/bgyl6eydrbioo4v/Kill%20Team%20List%20-%20Tau%20Empire%20v2.3.pdf?dl=0
